const KEY='family-finance-v203-fresh';
const FIXED=[['芋泥生活費',12000],['孝親費',12000],['大寶生活費',1200],['二寶生活費',400],['保險',16500],['信貸①',7496],['信貸②',6100],['信貸③',6844],['安親班',8600],['英文',7600],['ETC',3000],['電話',4000],['長照',1500],['捐款＋ETF',2600],['你的生活費',7000]];
const CARDS=[
 {id:'ctbc',name:'中國信託',close:25,mode:'statement',limit:200000,currentDue:180143,actual:195143,min:14200,baseDate:'2026-10-07'},
 {id:'fubon',name:'台北富邦',close:24,mode:'statement',limit:100000,currentDue:0,actual:20939,min:7103,baseDate:'2026-10-07',installments:[{name:'小林鐘錶眼鏡股份有限公司',current:2,total:3,amount:1260},{name:'富邦momo-EC',current:4,total:6,amount:4289}]},
 {id:'yuni',name:'芋泥台北富邦',close:8,mode:'monthly'},
 {id:'cathay',name:'國泰世華',close:17,mode:'monthly'},
 {id:'yuanta',name:'元大信用卡',close:26,mode:'statement',currentDue:3583,actual:3583,min:0,baseDate:'2026-10-07',installments:[{name:'遠傳電信股份有限公司',current:6,total:8,amount:953},{name:'Dr.A3C 快速維修中心 A',current:5,total:8,amount:500},{name:'Dr.A3C 快速維修中心 B',current:5,total:8,amount:606},{name:'樂購蝦皮－尚捷電玩',current:1,total:8,amount:552}]},
 {id:'esun',name:'玉山銀行',close:13,mode:'monthly'}
];
const LOANS=[{name:'信貸①',principal:422574,payment:7496,start:'2025-10-01',end:'2032-10-01'},{name:'信貸②',principal:298073,payment:6100,start:'2024-04-12',end:'2031-04-12'},{name:'信貸③',principal:219138,payment:6844,start:'2022-07-14',end:'2029-07-14'}];
const defaultState=()=>({version:2,income:{yuni:67000,user:33000,other:8000},fixed:FIXED.map(([name,amount])=>({id:crypto.randomUUID(),name,amount})),wallets:{cash:0,line:0},expenses:[],incomes:[],borrowPeople:[{name:'姐姐',balance:0,repaid:0},{name:'大寶',balance:0,repaid:0},{name:'二寶',balance:0,repaid:0},{name:'三寶',balance:0,repaid:0}],borrowLedger:[],cards:structuredClone(CARDS),loans:structuredClone(LOANS),loanExtra:[],loanHistory:[],cardPayments:{}});
let state=load(), view='budget', month=ym(new Date());
function load(){try{const s=JSON.parse(localStorage.getItem(KEY))||defaultState();if(!s.cardPayments)s.cardPayments={};if(!Array.isArray(s.loanHistory))s.loanHistory=[];const defaults=structuredClone(CARDS);if(!Array.isArray(s.cards))s.cards=defaults;else{s.cards=defaults.map(d=>{const old=s.cards.find(c=>c.id===d.id)||{};const merged={...d,...old};if(d.id==='ctbc')Object.assign(merged,{name:d.name,close:25,mode:'statement',limit:200000,currentDue:180143,actual:195143,min:14200,baseDate:'2026-10-07'});if(d.id==='fubon')Object.assign(merged,{name:d.name,close:24,mode:'statement',limit:100000,currentDue:0,actual:20939,min:7103,baseDate:'2026-10-07',installments:d.installments});if(d.id==='yuanta')Object.assign(merged,{name:d.name,close:26,mode:'statement',currentDue:3583,actual:3583,min:0,baseDate:'2026-10-07',installments:d.installments});delete merged.paid;delete merged.available;return merged})}if(!Array.isArray(s.borrowPeople))s.borrowPeople=defaultState().borrowPeople; s.borrowPeople.forEach(p=>{delete p.available; const ledgerRepaid=sum((s.borrowLedger||[]).filter(x=>x.person===p.name&&x.type==='repay'),x=>x.amount); if(p.repaid==null)p.repaid=ledgerRepaid;});return s}catch{return defaultState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function ym(d){return d.toISOString().slice(0,7)} function fmt(n){return '$'+Math.round(Number(n)||0).toLocaleString('zh-TW')} function sum(a,f=x=>x){return a.reduce((s,x)=>s+(Number(f(x))||0),0)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function monthExpenses(){return state.expenses.filter(x=>x.date?.slice(0,7)===month)} function monthIncomes(){return state.incomes.filter(x=>x.date?.slice(0,7)===month)}
function monthlyCardSpend(id){return sum(monthExpenses().filter(x=>x.pay===id),x=>x.amount)}
function cardDue(c){if(c.mode==='monthly')return monthlyCardSpend(c.id); if(month==='2026-10')return Number(c.currentDue??c.actual)||0; return installmentDue(c,month)+monthlyCardSpend(c.id)}
function installmentMonthRows(c,m){if(!c.installments?.length)return [];const [Y,M]=m.split('-').map(Number),[bY,bM]=(c.baseDate||'2026-10').slice(0,7).split('-').map(Number);const diff=(Y-bY)*12+(M-bM);if(diff<0)return [];return c.installments.map(i=>({...i,shown:i.current+diff})).filter(i=>i.shown>=1&&i.shown<=i.total)}
function installmentDue(c,m){if(!c.installments?.length)return 0;const [Y,M]=m.split('-').map(Number),[bY,bM]=(c.baseDate||'2026-10').slice(0,7).split('-').map(Number);const diff=(Y-bY)*12+(M-bM);if(diff<=0)return 0;return sum(installmentMonthRows(c,m),i=>i.amount)}
function fixedTotal(){return sum(state.fixed,x=>x.amount)} function incomeTotal(){return sum(Object.values(state.income))+sum(monthIncomes(),x=>x.amount)}
function nonFixedSpend(){return sum(monthExpenses().filter(x=>!state.cards.some(c=>c.id===x.pay)),x=>x.amount)}
function suggestedCardDue(){return sum(state.cards,c=>cardDue(c))}
function actualCardPayment(){return Number(state.cardPayments?.[month])||0}
function setCardPayment(v){if(!state.cardPayments)state.cardPayments={};state.cardPayments[month]=Math.max(0,Number(v)||0);save()}
function status(balance){return balance<0?['🔴 本月已超支','bad']:balance<5000?['🟡 接近上限','warn']:['🟢 還有餘裕','good']}
function render(){document.getElementById('app').innerHTML=`<main class="shell"><div class="top"><div><div class="title">一家五口家庭財務</div></div><div class="monthbar"><button class="iconbtn" onclick="moveMonth(-1)">‹</button><b>${month.replace('-','年')}月</b><button class="iconbtn" onclick="moveMonth(1)">›</button></div></div>${({budget:budgetView,today:todayView,cards:cardsView,borrow:borrowView,loans:loansView,system:systemView})[view]()} </main>${nav()}`}
function nav(){return `<nav class="nav">${[['budget','預算'],['today','今日開銷'],['cards','信用卡'],['borrow','借款'],['loans','貸款'],['system','系統']].map(([v,t])=>`<button class="${view===v?'active':''}" onclick="view='${v}';render()">${t}</button>`).join('')}</nav>`}
function budgetView(){const inc=incomeTotal(), fixed=fixedTotal(), suggested=suggestedCardDue(), cards=actualCardPayment(), spend=nonFixedSpend(), bal=inc-fixed-cards-spend, st=status(bal);return `<div class="grid"><div class="card"><div class="muted">本月收入</div><div class="metric">${fmt(inc)}</div><button class="btn ghost small" onclick="incomeBaseModal()">調整每月收入</button></div><div class="card"><div class="muted">固定底盤</div><div class="metric">${fmt(fixed)}</div></div></div><div class="card ${st[1]}"><div class="muted">本月預估結餘</div><div class="metric">${fmt(bal)}</div><b>${st[0]}</b></div><div class="card"><h3>本月預算拆解</h3><div class="row"><span>收入</span><span class="money">${fmt(inc)}</span></div><div class="row"><span>固定支出</span><span class="money">− ${fmt(fixed)}</span></div><div class="row"><div><span>本月信用卡實際繳款</span><div class="muted">帳單／本月消費參考 ${fmt(suggested)}，可依實際繳最低或自行輸入</div></div><div style="width:125px"><input type="number" min="0" value="${cards}" onchange="setCardPayment(this.value)" style="text-align:right"></div></div><div class="row"><span>其他非固定支出</span><span class="money">− ${fmt(spend)}</span></div><div class="row totalrow"><b>收入 − 固定支出 − 信用卡 − 其他支出</b><b class="money">${fmt(bal)}</b></div></div><div class="card"><h3>目前資金</h3><div class="row"><span>💵 手頭現金</span><span class="money">${fmt(state.wallets.cash)}</span></div><div class="row"><span>📱 LINE Pay Money</span><span class="money">${fmt(state.wallets.line)}</span></div><button class="btn ghost" onclick="walletModal()">調整錢包</button></div><div class="card"><h3>每月固定支出 <span class="pill">${fmt(fixedTotal())}</span></h3>${state.fixed.map(x=>`<div class="row"><span>${esc(x.name)}</span><span class="money">${fmt(x.amount)}</span></div>`).join('')}<button class="btn ghost" onclick="fixedModal()">編輯固定支出</button></div>`}

function incomeBaseModal(){modal({title:'調整每月收入',body:`<div class="muted" style="margin-bottom:10px">這裡是每月收入底盤；「今日收支」新增的臨時收入仍會另外加到當月。</div><div class="field"><label>芋泥薪資</label><input id="ibYuni" type="number" min="0" value="${Number(state.income.yuni)||0}"></div><div class="field"><label>你的薪資</label><input id="ibUser" type="number" min="0" value="${Number(state.income.user)||0}"></div><div class="field"><label>其他／補助</label><input id="ibOther" type="number" min="0" value="${Number(state.income.other)||0}"></div><button class="fab" onclick="saveIncomeBase()">儲存收入底盤</button>`})}
function saveIncomeBase(){state.income.yuni=Math.max(0,Number(ibYuni.value)||0);state.income.user=Math.max(0,Number(ibUser.value)||0);state.income.other=Math.max(0,Number(ibOther.value)||0);closeModal();save()}
function todayView(){const ex=monthExpenses(),ins=monthIncomes(),xs=[...ex.map(x=>({...x,kind:'expense'})),...ins.map(x=>({...x,kind:'income'}))].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="card"><h3>今日收支 V2</h3><div class="actions"><button class="fab" onclick="expenseModal()">－ 新增開銷</button><button class="btn pink" onclick="incomeModal()">＋ 新增收入</button></div><div class="grid" style="margin-top:10px"><div><div class="muted">本月開銷</div><b>${fmt(sum(ex,x=>x.amount))}</b></div><div><div class="muted">本月新增收入</div><b>${fmt(sum(ins,x=>x.amount))}</b></div></div><div class="grid" style="margin-top:8px"><div><div class="muted">信用卡消費</div><b>${fmt(sum(ex.filter(x=>state.cards.some(c=>c.id===x.pay)),x=>x.amount))}</b></div><div></div></div></div><div class="card"><h3>本月收支明細</h3>${xs.length?xs.map(x=>x.kind==='expense'?`<div class="row"><div><b>支出・${esc(x.category)}</b><div class="muted">${x.date}・${payName(x.pay)}${x.note?'・'+esc(x.note):''}</div></div><div class="right"><div class="money">− ${fmt(x.amount)}</div><button class="btn ghost small" onclick="deleteExpense('${x.id}')">刪除</button></div></div>`:`<div class="row"><div><b>收入・${esc(x.category)}</b><div class="muted">${x.date}・${incomeDestName(x.dest)}${x.note?'・'+esc(x.note):''}</div></div><div class="right"><div class="money">＋ ${fmt(x.amount)}</div><button class="btn ghost small" onclick="deleteIncome('${x.id}')">刪除</button></div></div>`).join(''):'<div class="empty">本月還沒有收支紀錄</div>'}</div>`}
function cardsView(){return `<div class="card"><h3>信用卡 V2</h3><div class="muted">刷卡紀錄、實際帳單與分期分開管理；分期會依月份自動推進，最後一期結束後下個月自動隱藏。</div></div>${state.cards.map(c=>{const due=cardDue(c),spend=monthlyCardSpend(c.id),rows=installmentMonthRows(c,month);return `<div class="card"><h3>${esc(c.name)} <span class="pill">結帳日 ${c.close}</span></h3><div class="row"><span>本月目前應繳</span><b>${fmt(due)}</b></div><div class="row"><span>本月新刷卡</span><b>${fmt(spend)}</b></div><div class="row"><span>${Number(month.slice(5))}月實際帳單</span><b>${fmt(month==='2026-10'?(c.actual||0):0)}</b></div><div class="row"><span>最低應繳</span><b>${fmt(month==='2026-10'?(c.min||0):0)}</b></div>${c.installments?.length?`<div class="sectiontitle">${month.replace('-','年')}月分期</div>${rows.length?rows.map(i=>`<div class="row"><div>${esc(i.name)}<div class="muted">本月 ${String(i.shown).padStart(2,'0')}/${String(i.total).padStart(2,'0')} 期</div></div><b>${fmt(i.amount)}/期</b></div>`).join(''):'<div class="empty">本月已無進行中的分期</div>'}`:''}</div>`}).join('')}`}
function borrowView(){const total=sum(state.borrowPeople,x=>x.balance);return `<div class="card"><h3>私人借款</h3><div class="metric">${fmt(total)}</div><div class="muted">借款預設不列入手頭現金</div><button class="fab" onclick="borrowModal()">＋ 借款／還款</button></div>${state.borrowPeople.map((p,i)=>`<div class="card"><div class="row"><b>${esc(p.name)}</b><span class="money">目前欠 ${fmt(p.balance)}</span></div><div class="row"><span>已還款金額</span><span>${fmt(p.repaid||0)}</span></div><button class="btn ghost" onclick="editBorrowPerson(${i})">設定</button></div>`).join('')}<div class="card"><h3>借還紀錄</h3>${state.borrowLedger.length?state.borrowLedger.slice().reverse().map(x=>`<div class="row"><div><b>${esc(x.person)}・${x.type==='borrow'?'借款':'還款'}</b><div class="muted">${x.date}${x.cash?'・有連動現金':'・未連動現金'}</div></div><b>${fmt(x.amount)}</b></div>`).join(''):'<div class="empty">尚無紀錄</div>'}</div>`}
function loansView(){return `<div class="card"><h3>銀行信貸</h3><div class="grid"><div><div class="muted">剩餘本金合計</div><b>${fmt(sum(state.loans,x=>x.principal))}</b></div><div><div class="muted">每月月繳</div><b>${fmt(sum(state.loans,x=>x.payment))}</b></div></div><div class="muted" style="margin-top:8px">月繳已包含在固定支出，不會重複扣款。</div><button class="btn pink" style="margin-top:12px" onclick="refinanceModal()">轉貸／整合完成</button></div>${state.loans.map((l,i)=>`<div class="card"><h3>${esc(l.name)}</h3><div class="row"><span>剩餘本金</span><b>${fmt(l.principal)}</b></div><div class="row"><span>每月繳款</span><b>${fmt(l.payment)}</b></div><div class="row"><span>期間</span><span class="small">${l.start||'—'}～${l.end||'—'}</span></div>${l.rate?`<div class="row"><span>年利率</span><span>${l.rate}%</span></div>`:''}<button class="btn ghost" onclick="loanExtraModal(${i})">＋ 額外還本金</button></div>`).join('')}${state.loanHistory?.length?`<div class="card"><h3>已結清／已轉貸紀錄</h3>${state.loanHistory.slice().reverse().map(h=>`<div class="row"><div><b>${esc(h.name)}</b><div class="muted">${h.closedDate||''}・因轉貸結清</div></div><span>${fmt(h.principal)}</span></div>`).join('')}</div>`:''}`}
function refinanceModal(){modal({title:'轉貸／整合完成',body:`<div class="muted" style="margin-bottom:10px">確認後，現有貸款會移到「已結清／已轉貸紀錄」，固定支出的舊貸款月繳也會移除，只保留新的轉貸月繳。</div><div class="field"><label>新貸款名稱</label><input id="rfName" value="新整合貸款"></div><div class="field"><label>新貸款本金</label><input id="rfPrincipal" type="number" min="0"></div><div class="field"><label>每月月繳</label><input id="rfPayment" type="number" min="0"></div><div class="grid"><div class="field"><label>貸款日期</label><input id="rfStart" type="date"></div><div class="field"><label>到期日</label><input id="rfEnd" type="date"></div></div><div class="field"><label>年利率 %（可不填）</label><input id="rfRate" type="number" step="0.01" min="0"></div><div class="field"><label>原貸款結清日</label><input id="rfClosed" type="date" value="${new Date().toISOString().slice(0,10)}"></div><button class="fab" onclick="applyRefinance()">確認轉貸並同步固定支出</button>`})}
function applyRefinance(){const name=rfName.value.trim()||'新整合貸款',principal=Math.max(0,+rfPrincipal.value||0),payment=Math.max(0,+rfPayment.value||0);if(!principal||!payment){alert('請輸入新貸款本金與每月月繳');return}if(!confirm('確定已完成轉貸？這會把目前貸款移到已結清紀錄，並同步更換固定支出的貸款月繳。'))return;const closedDate=rfClosed.value||new Date().toISOString().slice(0,10);state.loanHistory=[...(state.loanHistory||[]),...state.loans.map(l=>({...l,closedDate,reason:'refinance'}))];state.loans=[{name,principal,payment,start:rfStart.value,end:rfEnd.value,rate:Math.max(0,+rfRate.value||0)}];const oldLoanNames=new Set(['信貸①','信貸②','信貸③','整合貸款','新整合貸款',...state.loanHistory.map(x=>x.name)]);state.fixed=state.fixed.filter(x=>!oldLoanNames.has(x.name));state.fixed.push({id:crypto.randomUUID(),name,amount:payment});closeModal();save()}
function systemView(){return `<div class="card"><h3>資料與備份</h3><div class="row"><span>資料庫</span><b>Family Finance V2.0.8 Fresh</b></div><div class="row"><span>儲存方式</span><span>此裝置 localStorage</span></div><div class="actions"><button class="btn" onclick="exportData()">匯出備份</button><label class="btn ghost">匯入備份<input type="file" accept="application/json" style="display:none" onchange="importData(this)"></label></div></div><div class="card"><h3>診斷</h3><div class="row"><span>固定支出合計</span><b>${fmt(fixedTotal())}</b></div><div class="row"><span>信用卡數</span><b>${state.cards.length}</b></div><div class="row"><span>今日開銷筆數</span><b>${state.expenses.length}</b></div><div class="row"><span>私人借款紀錄</span><b>${state.borrowLedger.length}</b></div></div><div class="card bad"><h3>清除 V2 資料</h3><div class="muted">只會清除全新的 V2 資料，不會讀取或刪除舊版資料。</div><button class="btn danger" onclick="resetV2()">清除並重新開始</button></div>`}
function payName(id){return ({cash:'手頭現金',line:'LINE Pay Money',...Object.fromEntries(state.cards.map(c=>[c.id,c.name]))})[id]||id}
function moveMonth(n){let [y,m]=month.split('-').map(Number);m+=n;if(m<1){m=12;y--}if(m>12){m=1;y++}month=`${y}-${String(m).padStart(2,'0')}`;render()}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="sheet"><div class="sheethead"><h2>${html.title}</h2><button class="close" onclick="closeModal()">×</button></div>${html.body}</div></div>`)} function closeModal(){document.getElementById('modal')?.remove()}
function expenseModal(){modal({title:'新增開銷',body:`<div class="field"><label>日期</label><input id="eDate" type="date" value="${month}-${String(new Date().getDate()).padStart(2,'0')}"></div><div class="field"><label>金額</label><input id="eAmt" type="number"></div><div class="field"><label>分類</label><select id="eCat">${['餐飲','交通','日用品','小孩','醫療','娛樂','購物','旅遊','教育','保險','其他'].map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>付款方式</label><select id="ePay"><option value="cash">手頭現金</option><option value="line">LINE Pay Money</option>${state.cards.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>備註</label><input id="eNote"></div><button class="fab" onclick="addExpense()">儲存</button>`})}
function addExpense(){const amount=+eAmt.value;if(!amount)return;const x={id:crypto.randomUUID(),date:eDate.value,amount,category:eCat.value,pay:ePay.value,note:eNote.value};state.expenses.push(x);if(x.pay==='cash')state.wallets.cash-=amount;if(x.pay==='line')state.wallets.line-=amount;closeModal();save()}
function deleteExpense(id){const x=state.expenses.find(x=>x.id===id);if(!x||!confirm('刪除這筆開銷？'))return;if(x.pay==='cash')state.wallets.cash+=x.amount;if(x.pay==='line')state.wallets.line+=x.amount;state.expenses=state.expenses.filter(x=>x.id!==id);save()}
function incomeModal(){modal({title:'新增收入',body:`<div class="field"><label>日期</label><input id="iDate" type="date" value="${month}-${String(new Date().getDate()).padStart(2,'0')}"></div><div class="field"><label>金額</label><input id="iAmt" type="number" min="0"></div><div class="field"><label>收入類別</label><select id="iCat">${['薪資','補助','獎金','退款','回饋','臨時收入','其他'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>收入放哪裡</label><select id="iDest"><option value="none">只記收入，不調整錢包</option><option value="cash">手頭現金</option><option value="line">LINE Pay Money</option></select></div><div class="field"><label>備註</label><input id="iNote"></div><button class="fab" onclick="addIncome()">儲存收入</button>`})}
function addIncome(){const amount=+iAmt.value;if(!amount)return;const x={id:crypto.randomUUID(),date:iDate.value,amount,category:iCat.value,dest:iDest.value,note:iNote.value};state.incomes.push(x);if(x.dest==='cash')state.wallets.cash+=amount;if(x.dest==='line')state.wallets.line+=amount;closeModal();save()}
function deleteIncome(id){const x=state.incomes.find(x=>x.id===id);if(!x||!confirm('刪除這筆收入？'))return;if(x.dest==='cash')state.wallets.cash-=x.amount;if(x.dest==='line')state.wallets.line-=x.amount;state.incomes=state.incomes.filter(x=>x.id!==id);save()}
function incomeDestName(id){return ({none:'只記收入',cash:'手頭現金',line:'LINE Pay Money'})[id]||'只記收入'}
function walletModal(){modal({title:'調整錢包',body:`<div class="field"><label>手頭現金目前餘額</label><input id="wCash" type="number" value="${state.wallets.cash}"></div><div class="field"><label>LINE Pay Money 目前餘額</label><input id="wLine" type="number" value="${state.wallets.line}"></div><button class="fab" onclick="state.wallets.cash=+wCash.value||0;state.wallets.line=+wLine.value||0;closeModal();save()">儲存</button>`})}
function fixedModal(){modal({title:'編輯固定支出',body:`<div id="fixedEditor">${state.fixed.map((x,i)=>fixedEditorRow(x,i)).join('')}</div><button class="btn ghost" onclick="addFixedEditorRow()">＋ 增加固定支出項目</button><button class="fab" onclick="saveFixedEditor()">儲存</button>`})}
function fixedEditorRow(x,i){return `<div class="grid" id="fr${i}"><div class="field"><label>項目</label><input class="fixed-name" value="${esc(x?.name||'')}"></div><div class="field"><label>金額</label><input class="fixed-amount" type="number" min="0" value="${Number(x?.amount)||0}"></div></div>`}
function addFixedEditorRow(){const box=document.getElementById('fixedEditor'),i=box.querySelectorAll('.fixed-name').length;box.insertAdjacentHTML('beforeend',fixedEditorRow({name:'',amount:0},i));box.querySelectorAll('.fixed-name')[i].focus()}
function saveFixedEditor(){const names=[...document.querySelectorAll('.fixed-name')],amounts=[...document.querySelectorAll('.fixed-amount')];state.fixed=names.map((el,i)=>({id:state.fixed[i]?.id||crypto.randomUUID(),name:el.value.trim(),amount:Math.max(0,Number(amounts[i].value)||0)})).filter(x=>x.name);closeModal();save()}
function borrowModal(){modal({title:'借款／還款',body:`<div class="field"><label>對象</label><select id="bPerson">${state.borrowPeople.map((p,i)=>`<option value="${i}">${p.name}</option>`)}</select></div><div class="field"><label>類型</label><select id="bType"><option value="borrow">借款</option><option value="repay">還款</option></select></div><div class="field"><label>日期</label><input id="bDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>金額</label><input id="bAmt" type="number"></div><label class="check"><input id="bCash" type="checkbox"> 這筆${''}連動手頭現金</label><div class="muted">借款：勾選才增加現金；還款：勾選才扣除現金。</div><button class="fab" onclick="addBorrow()">儲存</button>`})}
function addBorrow(){const i=+bPerson.value,a=+bAmt.value,t=bType.value,c=bCash.checked;if(!a)return;state.borrowPeople[i].balance+=t==='borrow'?a:-a;if(state.borrowPeople[i].balance<0)state.borrowPeople[i].balance=0;if(t==='repay')state.borrowPeople[i].repaid=(Number(state.borrowPeople[i].repaid)||0)+a;if(c)state.wallets.cash+=t==='borrow'?a:-a;state.borrowLedger.push({id:crypto.randomUUID(),person:state.borrowPeople[i].name,type:t,amount:a,date:bDate.value,cash:c});closeModal();save()}
function editBorrowPerson(i){const p=state.borrowPeople[i];modal({title:p.name+'設定',body:`<div class="field"><label>目前欠款</label><input id="bpBal" type="number" value="${p.balance}"></div><div class="field"><label>已還款金額</label><input id="bpRepaid" type="number" value="${p.repaid||0}"></div><button class="fab" onclick="state.borrowPeople[${i}].balance=+bpBal.value||0;state.borrowPeople[${i}].repaid=+bpRepaid.value||0;closeModal();save()">儲存</button>`})}
function loanExtraModal(i){const l=state.loans[i];modal({title:l.name+' 額外還本金',body:`<div class="field"><label>金額</label><input id="lxAmt" type="number"></div><div class="field"><label>日期</label><input id="lxDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><button class="fab" onclick="let a=+lxAmt.value||0;state.loans[${i}].principal=Math.max(0,state.loans[${i}].principal-a);state.loanExtra.push({loan:'${l.name}',amount:a,date:lxDate.value});closeModal();save()">確認還本金</button>`})}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`一家五口家庭財務V2-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.version!==2)throw 0;if(confirm('匯入會覆蓋目前 V2 資料，確定嗎？')){state=d;save()}}catch{alert('這不是有效的 V2 備份檔')}};r.readAsText(f)}
function resetV2(){if(confirm('確定清除「一家五口家庭財務 V2」全部資料？')&&confirm('再次確認：此動作無法復原。')){localStorage.removeItem(KEY);state=defaultState();save()}}
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js?v=2.1.0');
